services:

  caddy:
    restart: "no"
    depends_on:
      - backend
      - frontend
    ports: !override
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
      CADDY_ADMIN_EMAIL: ${CADDY_ADMIN_EMAIL:-}

  db:
    restart: "no"
    ports: !override
      - "5433:5432"

  adminer:
    profiles: ["adminer"]
    image: adminer
    restart: "no"
    depends_on:
      - db
    ports: !override
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pepa-linha-dark

  backend:
    restart: "no"
    ports: !override
      - "8000:8000"
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/htmlcov
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  mailcatcher:
    profiles: ["mailcatcher", "playwright"]
    image: schickling/mailcatcher
    ports: !override
      - "1080:1080"
      - "1025:1025"

  frontend:
    restart: "no"
    ports: !override
      - "5173:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development

  playwright:
    profiles: ["playwright"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.playwright
      args:
        - VITE_API_URL=http://backend:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
      - mailcatcher
    env_file:
      - .env
      - ${COMPOSE_ENV_FILE:-.env}
    environment:
      - VITE_API_URL=http://backend:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      # For the reports when run locally
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/blob-report
      - ./frontend/test-results:/app/test-results
    ports: !override
      - 9323:9323
