# Dockerfile
FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install 'fastapi[standard]'

# bash conditional to verify if requirements.txt exists and install dependencies
RUN if [ -f requirements.txt ]; then \
    pip install -r requirements.txt; \
    else \
    echo "No requirements.txt file found, there is not extra dependencies to install"; \
    fi

CMD ["sh", "-c", "fastapi run --host 0.0.0.0 --port ${PORT:-8000}"]
