FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

# Install uv
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
COPY --from=ghcr.io/astral-sh/uv:0.4.23 /uv /bin/uv

# Compile bytecode
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#compiling-bytecode
ENV UV_COMPILE_BYTECODE=1

# uv Cache
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#caching
ENV UV_LINK_MODE=copy

# Set up user
RUN useradd --create-home -r user -u 1000

WORKDIR /app/

# When not run with BuildKit, the directory still belongs to root
RUN chown user /app

# Set user by non-root ID for Knative security compatibility
USER 1000

# Place executables in the environment at the front of the path
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#using-the-environment
ENV PATH="/app/.venv/bin:$PATH"

COPY --chown=user:user requirements.txt .

# Install dependencies
# No --mount because it requires BuildKit, not plain Docker
RUN uv venv && uv pip install -r requirements.txt

COPY --chown=user:user . .

CMD ["sh", "-c", "fastapi run --host 0.0.0.0 --port ${PORT:-8000}"]
