"""Add column deleted_at to App model

Revision ID: 073992e79634
Revises: 6a95f195ffb2
Create Date: 2025-07-24 13:24:37.056960

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '073992e79634'
down_revision = '6a95f195ffb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'deleted_at')
    # ### end Alembic commands ###
