"""Add default=False for registered_from_cli

The migration before this one (991ccb025dd3) was manually modified to have
server_default='FALSE' so that it can run in production, with existing data that
can't be converted to NULL, which would be the default if there was no server default.

But staging had already applied the previous migration before it was modified, so
this migration is needed to add the server default to the column in staging.

It's sort of a dirty hack. With a long comment for the next poor soul that needs to
deal with Alembic.

Revision ID: 0aa1b2f3680c
Revises: 991ccb025dd3
Create Date: 2025-05-08 21:36:16.076297

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0aa1b2f3680c'
down_revision = '991ccb025dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitinglistuser', 'registered_from_cli', server_default='FALSE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
