"""Add column cleaned_up_at to App model

Revision ID: 24bbf72483ad
Revises: 73623a80510e
Create Date: 2025-07-24 14:28:18.683404

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '24bbf72483ad'
down_revision = '73623a80510e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('cleaned_up_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'cleaned_up_at')
    # ### end Alembic commands ###
