"""Add column personal_team_id to User model

Revision ID: 30a55259019b
Revises: 4df8ae4a83c0
Create Date: 2024-06-11 10:25:09.111475

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30a55259019b'
down_revision = '4df8ae4a83c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personal_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'team', ['personal_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'personal_team_id')
    # ### end Alembic commands ###
