"""Add app and deployment models

Revision ID: 341d6070ddb9
Revises: b7b546eac017
Create Date: 2024-08-12 20:19:40.963410

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '341d6070ddb9'
down_revision = 'b7b546eac017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('deployment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('waiting_upload', 'building', 'deploying', 'success', 'failed', name='deploymentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('invitation_team_id_fkey', 'invitation', type_='foreignkey')
    op.drop_constraint('invitation_invited_by_id_fkey', 'invitation', type_='foreignkey')
    op.create_foreign_key(None, 'invitation', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invitation', 'user', ['invited_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('userteamlink_user_id_fkey', 'userteamlink', type_='foreignkey')
    op.drop_constraint('userteamlink_team_id_fkey', 'userteamlink', type_='foreignkey')
    op.create_foreign_key(None, 'userteamlink', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'userteamlink', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userteamlink', type_='foreignkey')
    op.drop_constraint(None, 'userteamlink', type_='foreignkey')
    op.create_foreign_key('userteamlink_team_id_fkey', 'userteamlink', 'team', ['team_id'], ['id'])
    op.create_foreign_key('userteamlink_user_id_fkey', 'userteamlink', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'invitation', type_='foreignkey')
    op.drop_constraint(None, 'invitation', type_='foreignkey')
    op.create_foreign_key('invitation_invited_by_id_fkey', 'invitation', 'user', ['invited_by_id'], ['id'])
    op.create_foreign_key('invitation_team_id_fkey', 'invitation', 'team', ['team_id'], ['id'])
    op.drop_table('deployment')
    op.drop_table('app')
    # ### end Alembic commands ###
