"""Add environment variable model

Revision ID: 35527fb53dc1
Revises: 341d6070ddb9
Create Date: 2024-10-01 14:40:21.813013

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '35527fb53dc1'
down_revision = '341d6070ddb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmentvariable',
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environmentvariable')
    # ### end Alembic commands ###
