"""Add provider username to social accounts

Revision ID: 67c32b690671
Revises: 954dd9bb6388
Create Date: 2025-06-09 11:26:47.586032

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '67c32b690671'
down_revision = '954dd9bb6388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialaccount', sa.Column('provider_username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socialaccount', 'provider_username')
    # ### end Alembic commands ###
