"""Add status on apps

Revision ID: 6a95f195ffb2
Revises: 67c32b690671
Create Date: 2025-06-26 14:09:48.684120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a95f195ffb2'
down_revision = '67c32b690671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('active', 'pending_deletion', name='appstatus').create(op.get_bind())
    op.add_column('app', sa.Column('status', postgresql.ENUM('active', 'pending_deletion', name='appstatus', create_type=False), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'status')
    sa.Enum('active', 'pending_deletion', name='appstatus').drop(op.get_bind())
    # ### end Alembic commands ###
