"""Remove column status from App model

Revision ID: 73623a80510e
Revises: 073992e79634
Create Date: 2025-07-24 14:15:21.792115

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73623a80510e'
down_revision = '073992e79634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'status')
    sa.Enum('active', 'pending_deletion', name='appstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('active', 'pending_deletion', name='appstatus').create(op.get_bind())
    op.add_column('app', sa.Column('status', postgresql.ENUM('active', 'pending_deletion', name='appstatus', create_type=False), server_default=sa.text("'active'::appstatus"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
