"""Add token information to accounts

Revision ID: 954dd9bb6388
Revises: ccb9aa8fcf75
Create Date: 2025-05-20 15:22:11.751283

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '954dd9bb6388'
down_revision = 'ccb9aa8fcf75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialaccount', sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('socialaccount', sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('socialaccount', sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('socialaccount', sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socialaccount', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socialaccount', 'refresh_token_expires_at')
    op.drop_column('socialaccount', 'access_token_expires_at')
    op.drop_column('socialaccount', 'refresh_token')
    op.drop_column('socialaccount', 'access_token')
    op.drop_column('socialaccount', 'scope')
    # ### end Alembic commands ###
