"""Update waitlist fields

Revision ID: 991ccb025dd3
Revises: c73fdae02f53
Create Date: 2025-05-05 15:43:10.493819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '991ccb025dd3'
down_revision = 'c73fdae02f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitinglistuser', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('waitinglistuser', sa.Column('secret_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('waitinglistuser', sa.Column('registered_from_cli', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.alter_column('waitinglistuser', 'team_size',
               existing_type=postgresql.ENUM('myself', 'small', 'medium', 'large', 'enterprise', name='teamsize'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.drop_column('waitinglistuser', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitinglistuser', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('waitinglistuser', 'team_size',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=postgresql.ENUM('myself', 'small', 'medium', 'large', 'enterprise', name='teamsize'),
               existing_nullable=True)
    op.drop_column('waitinglistuser', 'registered_from_cli')
    op.drop_column('waitinglistuser', 'secret_code')
    op.drop_column('waitinglistuser', 'location')
    # ### end Alembic commands ###
