"""Add created_at to team

Revision ID: a63c538f8962
Revises: 89c9a00d523e
Create Date: 2024-07-23 11:08:12.380446

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a63c538f8962'
down_revision = '89c9a00d523e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.add_column('team', sa.Column('is_personal_team', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'team', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_personal_team_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'personal_team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personal_team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_personal_team_id_fkey', 'user', 'team', ['personal_team_id'], ['id'])
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'is_personal_team')
    op.drop_column('team', 'owner_id')
    # ### end Alembic commands ###
