"""Increase max size of WaitingListUser.use_case to 10,000

Revision ID: b252a79ae9da
Revises: 24bbf72483ad
Create Date: 2025-08-09 20:36:38.135843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b252a79ae9da'
down_revision = '24bbf72483ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitinglistuser', 'use_case',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitinglistuser', 'use_case',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
