"""Add newsletter_synced_at to WaitingListUser

Revision ID: b5fdf66dc755
Revises: b252a79ae9da
Create Date: 2025-08-11 13:30:35.297391

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b5fdf66dc755'
down_revision = 'b252a79ae9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitinglistuser', sa.Column('newsletter_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_waitinglistuser_newsletter_synced_at'), 'waitinglistuser', ['newsletter_synced_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitinglistuser_newsletter_synced_at'), table_name='waitinglistuser')
    op.drop_column('waitinglistuser', 'newsletter_synced_at')
    # ### end Alembic commands ###
