"""Add created_at to team

Revision ID: b7b546eac017
Revises: a63c538f8962
Create Date: 2024-07-24 20:53:15.638950

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b7b546eac017'
down_revision = 'a63c538f8962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'created_at')
    # ### end Alembic commands ###
