"""Remove invited_user_id column and relationships

Revision ID: c5cc3b0f01d6
Revises: a9b76125b71a
Create Date: 2024-05-24 15:47:43.647737

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5cc3b0f01d6'
down_revision = 'a9b76125b71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitation', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('invitation_invited_user_id_fkey', 'invitation', type_='foreignkey')
    op.drop_column('invitation', 'invited_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('invited_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('invitation_invited_user_id_fkey', 'invitation', 'user', ['invited_user_id'], ['id'])
    op.alter_column('invitation', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
