"""Make team size an enum

Revision ID: c73fdae02f53
Revises: 20493afff640
Create Date: 2025-01-23 11:21:23.800720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c73fdae02f53'
down_revision = '20493afff640'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type first
    op.execute("CREATE TYPE teamsize AS ENUM ('myself', 'small', 'medium', 'large', 'enterprise')")

    # Drop the existing column and create it fresh with the new type
    op.drop_column('waitinglistuser', 'team_size')
    op.add_column('waitinglistuser', sa.Column('team_size',
        sa.Enum('myself', 'small', 'medium', 'large', 'enterprise', name='teamsize'),
        nullable=True))

    op.create_index(op.f('ix_waitinglistuser_allowed_at'), 'waitinglistuser', ['allowed_at'], unique=False)
    op.create_index(op.f('ix_waitinglistuser_email'), 'waitinglistuser', ['email'], unique=False)
    op.create_index(op.f('ix_waitinglistuser_invitation_sent_at'), 'waitinglistuser', ['invitation_sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitinglistuser_invitation_sent_at'), table_name='waitinglistuser')
    op.drop_index(op.f('ix_waitinglistuser_email'), table_name='waitinglistuser')
    op.drop_index(op.f('ix_waitinglistuser_allowed_at'), table_name='waitinglistuser')
    op.drop_column('waitinglistuser', 'team_size')
    # Drop the enum type after reverting the column
    op.execute("DROP TYPE teamsize")
    # ### end Alembic commands ###
