"""Add enum-generate

Revision ID: ee02f4d74312
Revises: 0aa1b2f3680c
Create Date: 2025-05-08 23:43:37.148602

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'ee02f4d74312'
down_revision = '0aa1b2f3680c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('myself', 'small', 'medium', 'large', 'enterprise', name='teamsize').drop(op.get_bind())
    op.sync_enum_values(
        enum_schema='public',
        enum_name='deploymentstatus',
        new_values=['waiting_upload', 'ready_for_build', 'building', 'extracting', 'building_image', 'deploying', 'success', 'failed'],
        affected_columns=[TableReference(table_schema='public', table_name='deployment', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='deploymentstatus',
        new_values=['building', 'building_image', 'deploying', 'extracting', 'failed', 'ready_for_build', 'success', 'waiting_upload'],
        affected_columns=[TableReference(table_schema='public', table_name='deployment', column_name='status')],
        enum_values_to_rename=[],
    )
    sa.Enum('myself', 'small', 'medium', 'large', 'enterprise', name='teamsize').create(op.get_bind())
    # ### end Alembic commands ###
