"""Add slug column with unique and index constraint in Team table

Revision ID: f686be54aec9
Revises: a9b76125b71a
Create Date: 2024-05-25 00:20:58.980226

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f686be54aec9'
down_revision = 'a9b76125b71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitation', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('team', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_team_slug'), 'team', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_slug'), table_name='team')
    op.drop_column('team', 'slug')
    op.alter_column('invitation', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
