/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutResourcesImport } from './routes/_layout/resources'
import { Route as LayoutProjectsImport } from './routes/_layout/projects'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutHelpImport } from './routes/_layout/help'
import { Route as LayoutBillingImport } from './routes/_layout/billing'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutOrganizationsNewImport } from './routes/_layout/organizations/new'
import { Route as LayoutOrganizationsAllImport } from './routes/_layout/organizations/all'
import { Route as LayoutOrganizationInvitationsImport } from './routes/_layout/organization/invitations'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResourcesRoute = LayoutResourcesImport.update({
  path: '/resources',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsRoute = LayoutProjectsImport.update({
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHelpRoute = LayoutHelpImport.update({
  path: '/help',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBillingRoute = LayoutBillingImport.update({
  path: '/billing',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrganizationsNewRoute = LayoutOrganizationsNewImport.update({
  path: '/organizations/new',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrganizationsAllRoute = LayoutOrganizationsAllImport.update({
  path: '/organizations/all',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrganizationInvitationsRoute =
  LayoutOrganizationInvitationsImport.update({
    path: '/organization/invitations',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/billing': {
      preLoaderRoute: typeof LayoutBillingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/help': {
      preLoaderRoute: typeof LayoutHelpImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects': {
      preLoaderRoute: typeof LayoutProjectsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/resources': {
      preLoaderRoute: typeof LayoutResourcesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/organization/invitations': {
      preLoaderRoute: typeof LayoutOrganizationInvitationsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/organizations/all': {
      preLoaderRoute: typeof LayoutOrganizationsAllImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/organizations/new': {
      preLoaderRoute: typeof LayoutOrganizationsNewImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutBillingRoute,
    LayoutHelpRoute,
    LayoutItemsRoute,
    LayoutProjectsRoute,
    LayoutResourcesRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutOrganizationInvitationsRoute,
    LayoutOrganizationsAllRoute,
    LayoutOrganizationsNewRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
